### PR TITLE
Release version 0.0.4

### PR DESCRIPTION
**Pull request by mkcor**
Follows up wrt review of #9.

Will this create a conflict as I publish it on [PyPI](https://pypi.org/project/dash-bio-utils/#history)?

### CODE REVIEW

**Comment by mkcor** [comment]
Yes, it will, so I'll fix the CHANGELOG retroactively.

**Comment by mkcor** [comment]
@shammamah and yes, please, I would need publishing rights for https://pypi.org/project/dash-bio-utils as well as https://test.pypi.org/project/dash-bio-utils (will try this one first). Both accounts are 'mkcor' -- thank you!

**Comment by shammamah** [comment]
@mkcor You should have owner rights for both of those packages now. If possible, could you also use a release tag for this version?

**Comment by mkcor** [comment]
Ok! Shouldn't I create the release once these commits are into `master` though:
releases
? Thanks.

**Comment by mkcor** [comment]
> You should have owner rights for both of those packages now.

Thank you, it worked: https://pypi.org/project/dash-bio-utils/0.0.4/ :)

Could you please approve the PR?

**Comment by shammamah** [comment]
>Ok! Shouldn't I create the release once these commits are into master though:
Yep exactly. 

💃

**Comment by mkcor** [comment]
Great, thank you for the guidance! :heart: 
Done: https://github.com/plotly/dash-bio-utils/releases/tag/v0.0.4
I add the tarball manually; maybe that wasn't necessary?

**Pull request merged**
